services:
  postgres:
    image: postgres:15
    container_name: doc_postgres
    environment:
      POSTGRES_DB: documents
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  loader:
    build: .
    container_name: data_loader
    depends_on:
      - postgres
    command: python -m scripts.run_initial_load
    restart: "no"

  app:
    build: .
    container_name: doc_extractor_app
    depends_on:
      - postgres
      - loader
    ports:
      - "8501:8501"
    command: streamlit run app.py --server.port=8501 --server.address=0.0.0.0

volumes:
  postgres_data: